name: .NET Build & Test

on:
  push:
    branches: [ main, dev ]

  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, closed]

jobs:
  build_test:

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOs-latest' ]
        dotnet-version: [ '9.0' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Clean Project
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    # - name: Test Project
      # run: dotnet test --no-build --verbosity normal

    - name: Store Artifact
      uses: actions/upload-artifact@main
      with:
        name: Orbital Shell artifacts - ${{ matrix.os }}
        path: ./OrbitalShell-CLI/bin/Debug/net9.0/
